"""initial

Revision ID: d8676741a78b
Revises: 
Create Date: 2026-04-21 22:09:23.056427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8676741a78b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ggsel_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_api_token', sa.String(), nullable=True),
    sa.Column('seller_api_valid_thru', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_office_access_token', sa.String(), nullable=True),
    sa.Column('seller_office_refresh_token', sa.String(), nullable=True),
    sa.Column('seller_office_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('ggsel_offer_id', sa.Integer(), nullable=True),
    sa.Column('ggsel_id_goods', sa.Integer(), nullable=True),
    sa.Column('ggsel_option_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending_create', 'draft', 'active', 'paused', 'error', name='offerstatus'), nullable=False),
    sa.Column('xpanda_price_usd', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ggsel_price_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xpanda_qty', sa.Integer(), nullable=True),
    sa.Column('price_hash', sa.String(length=16), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ggsel_id_goods'),
    sa.UniqueConstraint('ggsel_offer_id'),
    sa.UniqueConstraint('market_hash_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CREATE_OFFER', 'UPDATE_PRICE_BATCH', 'TOGGLE_STATUS_BATCH', 'DELIVER', 'MONITOR_DELIVERY', 'MARK_DELIVERED', 'TRADE_WATCH', name='taskkind'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('precheck', 'notification', name='webhookkind'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ggsel_order_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price_cents', sa.Integer(), nullable=True),
    sa.Column('steam_trade_url', sa.Text(), nullable=True),
    sa.Column('steam_partner', sa.String(), nullable=True),
    sa.Column('steam_token', sa.String(), nullable=True),
    sa.Column('buyer_email', sa.String(), nullable=True),
    sa.Column('buyer_ip', sa.String(), nullable=True),
    sa.Column('xpanda_purchase_id', sa.String(), nullable=True),
    sa.Column('xpanda_custom_id', sa.String(), nullable=True),
    sa.Column('xpanda_status', sa.String(), nullable=True),
    sa.Column('xpanda_error_code', sa.String(), nullable=True),
    sa.Column('exec_price_cents', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'dispatched', 'done', 'finalized', 'failed', 'needs_attention', name='deliverystatus'), nullable=False),
    sa.Column('ggsel_marked_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ggsel_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('webhook_events')
    op.drop_table('tasks')
    op.drop_table('offers')
    op.drop_table('ggsel_tokens')
    # ### end Alembic commands ###
